- helm-dash.el
1000 is saner than 100. 
Especially when looking for very general things like 'read'
> Increase max number of results

- helm-dash.el
By default, the Dash app installs docsets in ~/Library/Application Support/Dash/Docsets
When helm-dash-docsets-path has spaces in it, tar command fails on Mac OS X.
To handle that, I suggest adding shell-quote-argument around it.  Tested in Emacs 24.4.1 on Mac OS X 10.3
> Support spaces in helm-dash-docsets-path

- README.md
- helm-dash.el
- test/helm-dash-test.el
Ability to download user contributed docsets.  It uses kidd/dashes-to-dashes api as an adapter. In the future, probably official ones will go through there also.
The behaviour of the app should be the same, just call m-x helm-dash-install-user-docset. RET
@areina: we should  test it thoughfully before merge
> User docsets

- README.md
I don't think firefox browser functions work in some Emacs versions anymore. The following is a possible fix for those cases.
> FAQ addition

- helm-dash.el
Restore the `(shell-quote-argument (helm-dash-docsets-path))` from
79d4979a33eaa46e25fde87b4f0a332dff112fa9 that seems to have been lost in a
merge.
> Handle whitespace in docset folder path

- README.md
- helm-dash.el
Fixes #80.
stderr from sqlite3 is sent to a file, which is then displayed as a buffer if it contains any text after the command has finished. This is based on the `shell-command` function, which seems to be the only one which provides useful error handling (but `shell-command` is not general enough for us to use directly).
Additionally by using `call-process` instead of `call-process-shell-command` we get an error if the `sqlite3` command cannot be found (my comment below was wrong, I didn't reset the connections properly when I tested it).
Finally I thought that `helm-dash-sql` was getting a bit too complicated and messy after these changes, so I moved the parsing out into a separate function.
> Add display of errors from sqlite3 command

- helm-dash.el
The paths where dash itself installs the docsets is somewhat
unpredictable (#84) and can not be reliably determined from the docset
name/id alone. For example:
* Bootstrap_2 => Bootstrap_2/Bootstrap.docset
* Bootstrap_3 => Bootstrap_3/Bootstrap 3.docset
* Emacs_Lisp => Emacs_Lisp/Emacs Lisp.docset
Try harder to find them simply by looking inside the directory and
accepting the first *.docset directory present. The list of paths
searched is now:
* {name/id}.docset             -- helm-dash installation, probably
* {name/id}/{name/id}.docset   -- dash installation, e.g. Haskell
* {name/id}/*.docset           -- dash installation, e.g. Bootstrap_2
> Try harder to find dash installed docsets

- helm-dash.el
Key 'name is not necessarily in cdr
> BugFix: helm-dash-available-docsets  function

- helm-dash.el
From helm doc:
:history
By default all minibuffer input is pushed to `minibuffer-history',
if an argument HISTORY is provided, input will be pushed to HISTORY.
History element should be a symbol.
> Add history option for helm

- helm-dash.el
Enables a 'new' workflow of activating docsets in every session
Fixes #109
> Autoload helm-dash-activate-docset.

- helm-dash.el
In my setup `temporary-file-directory = "~/.emacs.d/backup"` and it cause error during unpacking.
This small patch should fix this.
> Fixes unpacking if `temporary-file-directory` contains "~"

- helm-dash.el
In db04dd562526163131, we introduced a bug that searched the db's just
on init, not following minimal-length or recalculating results. This
commit fixes it.
Fixes #124
> Candidates-process is called every keypress.

- helm-dash.el
- test/helm-dash-test.el
Details in the commit message.
Also removed an option from the call to `helm-build-sync-source` because it's deprecated and the latest version of helm opens an error window every time you run `helm-dash` telling you about it. I don't really understand what the `:delayed` is/was supposed to do, but helm-dash still "works-on-my-machine"...
> Fix issue #67 (no results in first call to helm-dash)

- helm-dash.el
Url fetching and tar unpacking are both done asynchronously.
Fixes #92.
It works on my machine!
> Add helm-dash-async-install-docset function

- README.md
Hi, was setting this up today and noticed this typo for the default value of `helm-dash-docsets-path` in the readme.
> Fixed README.md typo for the default helm-dash-docsets-path value

- helm-dash.el
With the `file://` prefix, eww thinks that you're trying to open an FTP connection. However, with `file:///` (note the additional slash), everything works fine.
Same patch as ccea7c53caa51a37a3829e333ed745f6709a26ea, previously seen in #58. Was broken by db04dd5625261631311d68108a057a1d32fc69a4.
> Fix opening docs in eww in Windows (again)

- helm-dash.el
- test/helm-dash-test.el
These kind of tags were added recently in Dash docsets and aren't useful for
us, so we can remove them directly from the url.
Fixes #145
> Remove <dash_entry_.*> from documentation urls

- helm-dash.el
This pull request adds a function called `helm-dash-ensure-docset-installed` (as well as a small helper called `helm-dash-docset-installed-p`), which can be used to ensure a docset is installed.
The function can be used like this:
```elisp
(helm-dash-ensure-docset-installed "Ansible")
```
(See #152 for reference.)
> Add `helm-dash-ensure-docset-installed`

- helm-dash.el
helm-dash-at-point for text in readonly regions work properly now.
> Add unpropertize text on helm-dash-at-point.

- helm-dash.el
When point is on a space, blank line, punctuation etc. use a blank string as input instead to `nil` to avoid "Wrong type argument: stringp, nil" from `substring-no-properties`.
The problem was probably introduced recently in b7fbf789b83e290885e506e887f6ed9c5b858423.
> Fix helm-dash-at-point when no symbol at point

- helm-dash.el
Made tar extraction work on windows, along with some added niceties like filename transformation and detection of overlong filenames.
> Windows file fixes

- helm-dash.el
It seems spacemacs is calling this function from their layer:
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/dash/funcs.el#L14
Resolve #186
> Add alias for `helm-dash-installed-docsets`
